# Generated by Django 5.0.4 on 2024-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educational_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
