# Generated by Django 5.0.4 on 2024-04-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("educational_resources", "0002_resource_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="resources_images/"
            ),
        ),
    ]
