# Generated by Django 5.0.4 on 2024-04-15 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_alter_appointmentslot_specialist"),
        ("online_consultations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="user",
        ),
        migrations.AddField(
            model_name="consultation",
            name="issue",
            field=models.TextField(default="Не оставил сообщение"),
        ),
        migrations.AddField(
            model_name="consultation",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="appointments.appointmentslot",
            ),
        ),
    ]
