# Generated by Django 5.0.4 on 2024-04-15 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_consultations", "0003_consultation_consultation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="consultation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
