# Generated by Django 5.0.4 on 2024-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_consultations", "0004_consultation_consultation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="consultation_type",
            field=models.CharField(
                choices=[
                    ("general", "Общая консультация"),
                    ("special", "Специализированная консультация"),
                    ("follow_up", "Повторная консультация"),
                    ("emergency", "Экстренная консультация"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
