# Generated by Django 5.0.4 on 2024-04-16 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_specialist_age"),
        (
            "online_consultations",
            "0006_remove_consultation_slot_alter_consultation_patient",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="consultation_date",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="specialist",
        ),
        migrations.CreateModel(
            name="ConsultationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_slots",
                        to="clinic.specialist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="online_consultations.consultationslot",
            ),
        ),
    ]
