# Generated by Django 5.0.4 on 2024-04-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_consultations", "0007_remove_consultation_consultation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="slot",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="online_consultations.consultationslot",
            ),
        ),
    ]
