# Generated by Django 5.0.4 on 2024-04-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_consultations", "0008_alter_consultation_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="video_call_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session",
                        to="online_consultations.consultation",
                    ),
                ),
            ],
        ),
    ]
