# Generated by Django 5.0.4 on 2024-04-09 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="contact email"
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="contact phone"
            ),
        ),
        migrations.AddField(
            model_name="specialist",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specialist",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="specialist",
            name="languages",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="specialist",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="specialists_photos/",
                verbose_name="profile photo",
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="day of the week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="clinic.specialist",
                    ),
                ),
            ],
        ),
    ]
