# Generated by Django 5.0.4 on 2024-04-13 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "verbose_name": "специалист",
                "verbose_name_plural": "специалисты",
            },
        ),
        migrations.AlterField(
            model_name="specialist",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="контактный email"
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="контактный телефон"
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="education",
            field=models.TextField(blank=True, verbose_name="образование"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="experience_years",
            field=models.IntegerField(default=0, verbose_name="опыт работы"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="languages",
            field=models.CharField(blank=True, max_length=100, verbose_name="языки"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="specialists_photos/",
                verbose_name="фотография специалиста",
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="qualifications",
            field=models.TextField(verbose_name="квалификация"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="specialization",
            field=models.CharField(max_length=100, verbose_name="специализация"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
