# Generated by Django 5.0.4 on 2024-04-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_alter_specialist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
    ]
