# Generated by Django 5.0.4 on 2024-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_specialist_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("image_url", models.URLField(verbose_name="URL изображения")),
                ("description", models.TextField(verbose_name="Описание")),
                ("specs", models.TextField(verbose_name="Технические характеристики")),
            ],
        ),
    ]
