# Generated by Django 5.0.4 on 2024-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(default="Не указано", verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                default="Не указано", max_length=50, verbose_name="Страна"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                default="Не указано", max_length=150, verbose_name="ФИО"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Мужской"), ("female", "Женский")],
                max_length=10,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
