# Generated by Django 5.0.4 on 2024-04-12 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_diagnostic_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
