# Generated by Django 5.0.4 on 2024-04-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customuser_activation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="citizenship",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Гражданство"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                default="", max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Отчество"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="residence",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Место жительства"
            ),
        ),
    ]
