# Generated by Django 5.0.4 on 2024-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_remove_customuser_address_remove_customuser_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Мужской", "Мужской"), ("Женский", "Женский")],
                max_length=10,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
