# Generated by Django 5.0.4 on 2024-04-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentslot",
            name="doctor",
        ),
        migrations.AddField(
            model_name="appointmentslot",
            name="specialist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="clinic.specialist",
            ),
        ),
    ]
