# Generated by Django 5.0.4 on 2024-04-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appointmentslot_doctor_and_more"),
        ("clinic", "0002_alter_specialist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="specialist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="clinic.specialist",
            ),
            preserve_default=False,
        ),
    ]
