# Generated by Django 5.0.4 on 2024-04-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointmentslot_specialist"),
        ("clinic", "0002_alter_specialist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="specialist",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_slots",
                to="clinic.specialist",
            ),
        ),
    ]
